config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs
  resources :events
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :staff
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :phone, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :phone, :email, :password, :current_password)}
         end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_staff!, except: [:index, :show]
  before_action :correct_staff, only: [:edit, :update, :destroy]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    #@event = Event.new
    @event = current_staff.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    #@event = Event.new(event_params)
    @event = current_staff.events.build(event_params)


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_staff
    @event = current_staff.events.find_by(id: params[:id])
    redirect_to events_path, notice: "Not Authorized To Edit This Friend" if @event.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :no_of_participant, :date, :time, :staff_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_event.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @event.name %>
  </h1>
  <p class="lead">
    <%= @event.no_of_participant %>  | 
    <%= @event.date %>  |  
    <%= @event.time.strftime('%H:%M:%S') %>

  </p>
  <br/>

  <%= link_to 'Edit', edit_event_path(@event), class:"btn btn-secondary" %>
  <%= link_to 'Delete', @event, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
   
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :name, class:"form-control", placeholder:"Event Name" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :no_of_participant, class:"form-control", placeholder:"Number of participant" %>
  </div>

  <div class="field form-group">
    <%= form.date_field :date, class:"form-control", placeholder:"Date" %>
  </div>

  <div class="field form-group">
    <%= form.time_field :time, class:"form-control", placeholder:"Time" %>
  </div>
  <div class="field form-group">
    <%= form.number_field :staff_id, id: :event_staff_id, class:"form-control", value: current_staff.id, type: :hidden %>
  </div>
  
<br/>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<% if staff_signed_in? %>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>No of Participants</th>
        <th>Date</th>
        <th>Time</th>
        <th colspan="3"> </th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <% if event.staff == current_staff %>
        <tr>
          <td><%= event.name %></td>          
          <td><%= event.no_of_participant %></td>
          <td><%= event.date %></td>
          <td><%= event.time.strftime('%H:%M:%S') %></td>
          <td><%= link_to 'View', event, class: "btn btn-light btn-sm"  %></td>
          <td><%= link_to 'Edit', edit_event_path(event), class: "btn btn-light btn-sm" %></td>
          <td><%= link_to 'Delete', event, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger btn-sm" %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Event', new_event_path, class:"btn btn-secondary" %>
  <% else %>

<h1>Hello World!</h1>
This is my first Rails Webpage...

<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<%= render @event %>

<div>|
  <%= link_to "Back to events", events_path %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Event Management', root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
          <% if staff_signed_in? %>
      <li class="nav-item">
          <%= link_to "Add Event", new_event_path, class:"nav-link" %>
        </li>
      <li class="nav-item">
        <%= link_to "Events", events_path, class:"nav-link"%>
      </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_staff_session_path, method: :delete, data: { turbo_method: :delete}, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_staff_registration_path, class:"nav-link"%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_staff_registration_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_staff_session_path, class:"nav-link"%>
        </li>
      <% end %>
    </ul>

    <div class="gmailtext">
    <% if staff_signed_in? %>
      <%= current_staff.name %>
    <% end %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
  <h2>Events List</h2>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Number of Participants</th>
        <th>Date</th>
        <th>Time</th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>

        <tr>
          <td><%= event.name%></td>          
          <td><%= event.no_of_participant %></td>
          <td><%= event.date %></td>
          <td><%= event.time.strftime('%H:%M:%S') %></td>  
        </tr>

      <% end %>
    </tbody>
  </table>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Mosque Management App</title>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class="container">
    <br>
    <% if  notice%>
      <%= render 'layouts/alerts' %>
    <% end %>

      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>